"""empty message

Revision ID: 32fb0e46cb45
Revises: ec0691b2c7ba
Create Date: 2021-01-14 14:10:58.977855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32fb0e46cb45'
down_revision = 'ec0691b2c7ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_genre_genre', table_name='genre')
    op.create_index(op.f('ix_genre_genre'), 'genre', ['genre'], unique=True)
    op.drop_index('ix_publisher_name', table_name='publisher')
    op.create_index(op.f('ix_publisher_name'), 'publisher', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_publisher_name'), table_name='publisher')
    op.create_index('ix_publisher_name', 'publisher', ['name'], unique=False)
    op.drop_index(op.f('ix_genre_genre'), table_name='genre')
    op.create_index('ix_genre_genre', 'genre', ['genre'], unique=False)
    # ### end Alembic commands ###
