"""empty message

Revision ID: 3ee99338d7b4
Revises: c427db500d3f
Create Date: 2021-01-13 19:12:01.768187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ee99338d7b4'
down_revision = 'c427db500d3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('borrowed_book_card', 'date_of_borrow')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('borrowed_book_card', sa.Column('date_of_borrow', sa.DATE(), nullable=True))
    # ### end Alembic commands ###
