"""empty message

Revision ID: 4f0695f6d9b9
Revises: 32fb0e46cb45
Create Date: 2021-01-14 14:37:43.781599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f0695f6d9b9'
down_revision = '32fb0e46cb45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_book_title', table_name='book')
    op.create_index(op.f('ix_book_title'), 'book', ['title'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_book_title'), table_name='book')
    op.create_index('ix_book_title', 'book', ['title'], unique=False)
    # ### end Alembic commands ###
