"""empty message

Revision ID: 744433197e71
Revises: 3ee99338d7b4
Create Date: 2021-01-13 19:19:39.219892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '744433197e71'
down_revision = '3ee99338d7b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('borrowed_book_card', 'date_of_borrow')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('borrowed_book_card', sa.Column('date_of_borrow', sa.DATE(), nullable=True))
    # ### end Alembic commands ###
