"""empty message

Revision ID: af52d8886c3f
Revises: 5d27f4451a73
Create Date: 2021-01-13 18:53:30.526047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af52d8886c3f'
down_revision = '5d27f4451a73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('borrowed_book_card', sa.Column('date_of_borrow', sa.Date(), nullable=True))
    op.drop_column('borrowed_book_card', 'date_of_loan')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('borrowed_book_card', sa.Column('date_of_loan', sa.DATE(), nullable=True))
    op.drop_column('borrowed_book_card', 'date_of_borrow')
    # ### end Alembic commands ###
