"""empty message

Revision ID: c427db500d3f
Revises: af52d8886c3f
Create Date: 2021-01-13 19:00:23.233903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c427db500d3f'
down_revision = 'af52d8886c3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('borrowed_book_card', 'date_of_loan')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('borrowed_book_card', sa.Column('date_of_loan', sa.DATE(), nullable=True))
    # ### end Alembic commands ###
