"""empty message

Revision ID: ec0691b2c7ba
Revises: 744433197e71
Create Date: 2021-01-13 19:20:32.018961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec0691b2c7ba'
down_revision = '744433197e71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('borrowed_book_card', 'date_of_borrow')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('borrowed_book_card', sa.Column('date_of_borrow', sa.DATE(), nullable=True))
    # ### end Alembic commands ###
